### ISSUE TITLE
Dataset?

### ISSUE THREAD

**Issue by sohaiblaraba** [anindox8/Deep-Segmentation-Features-for-Weakly-Supervised-3D-Disease-Classification-in-Chest-CT#1]
Hello,

Nice work!
I'd like to know if there's an access to your dataset.

Thank you in advance

**Comment by anindox8** [comment]
Thank you. Unfortunately, the dataset is proprietary to Duke University Medical Center and is still under development. Hopefully, it'll be released publicly once it's fully curated.
